function ids = name2id(names)
% Function to translate metabolite names from the abundance dataset to
% identifiers in the AraCore model.

mapping = {...
    'Alanine'                           'Ala'
    'Asparagine'                        'Asn'
    'Aspartate'                         'Asp'
    'BetaAlanine'                       ''
    'Citrate'                           'Cit'
    'Fructose'                          'Frc'
    'Fumarate_carefulMaleic'            'Fum'
    'GABA'                              'GABA'
    'Glucose'                           'Glc'
    'Glutamate'                         'Glu'
    'Glutamine'                         'Gln'
    'Glycerate'                         'GCEA'
    'Glycerol'                          ''
    'Glycine'                           'Gly'
    'Glycolate'                         'GCA'
    'Isoleucine'                        'Ile'
    'Leucine'                           'Leu'
    'Lysine'                            'Lys'
    'Malate'                            'Mal'
    'Maltose'                           'Mas'
    'Methionine'                        'Met'
    'MyoInosirtol'                      ''
    'Nicotinamide'                      ''
    'Oxoglutarate'                      'KG'
    'Palmitate'                         ''
    'Phenylalanine'                     'Phe'
    'Phosphate'                         'Pi'
    'Proline'                           'Pro'
    'Putrescine'                        ''
    'Pyruvate'                          'Pyr'
    'Serine'                            'Ser'
    'Succinate'                         'SCA'
    'Sucrose_overload'                  'Suc'
    'Threitol'                          ''
    'ThreonicAcid'                      'Thr'
    'Tryptophan'                        'Trp'
    'Valine'                            'Val'
    'Starch'                            'starch2'
    'Nitrate'                           'NO3'
    'Arginine'                          'Arg'
    'Citrulline'                        'CTL'
    'Raffinose'                         ''
    'Shikimate'                         'SA'
    'Tyrosine'                          'Tyr'
    'UDP-Glucose'                       'UDPG'
    'Cysteine'                          'Cys'
    'Ornithine'                         'Orn'
    'Galactose'                         ''
    'Trehalose'                         'Tre'
    'Dihydroxyacetone'                  ''
    'Erythritol'                        ''
    'Galactinol'                        ''
    '4-Hydroxyproline'                  ''
    'Urea'                              'urea'
    'Xylose'                            ''
    'Guanidine'                         ''
    'Salicylate'                        ''
    'Histidine'                         'His'
    'Aconitate'                         'cACN'
    'ATP'                               'ATP'
    'ADP'                               'ADP'
    'AMP'                               'AMP'
    'ADP-Glucose'                       'ADPG'
    'Dihydroxyacetonephosphate'         'DHAP'
    'Fructose-6-phosphate'              'F6P'
    'Fructose-1,6-bisphosphate'         'FBP'
    'Glucose-1-phosphate'               'G1P'
    'Glyceraldehyde 3-phosphate'        'GAP'
    'Glucose 6-phosphate'               'G6P'
    'Isocitrate'                        'iCit'
    'NAD'                               'NAD'
    'NADP'                              'NADP'
    '3-Phosphoglyceric acid'            'PGA'
    'Phosphoenolpyruvate'               'PEP'
    'Ribose 5-phosphate'                'R5P'
    'Ribulose-1,5-Bisphosphate'         'RuBP'
    'Sedoheptulose 7-phosphate'         'S7P'
    'Sedoheptulose 1,7-bisphosphate'    'SBP'
    'Trehalose 6-phosphate'             'T6P'
    'Fucose'                            ''
    'Mannose'                           ''
    'Nicotinate'                        ''
    '2-Oxoglutarate'                    'KG'
    'Sucrose'                           'Suc'
    'Fumarate'                          'Fum'
    'Oxaloacetate'                      'OAA'
    'Threonine'                         'Thr'
    };

ids = cell(numel(names),1);
for i=1:numel(names)
    match_idx = ismember(mapping(:,1),names(i));
    if sum(match_idx)==1
        ids(i) = mapping(match_idx,2);
    else
        ids(i) = {''};
    end
end
    
end