% extract data from Excel spreadsheet and save them to csv

top_dir = '../Data';

%% dry weights
% ml
dw_tab = readtable(...
    fullfile(top_dir,'220404_AllData_Photorespiration_TB.xlsx'),...
    'Sheet', 'Dry Weight ML',...
    'Range', 'G:I'...
    );
dw_tab(cellfun(@isempty,dw_tab.Genotype),:) = [];
uniq_genotypes = unique(dw_tab.Genotype);
av_dw_34 = cellfun(@(x)...
    mean(...
        dw_tab.DryWeight_mg_(ismember(dw_tab.Genotype,x))/1000,...
        'omitnan'...
        ),...
    uniq_genotypes...
    );
sd_dw_34 = cellfun(@(x)...
    std(...
        dw_tab.DryWeight_mg_(ismember(dw_tab.Genotype,x))/1000,...
        'omitnan'...
        ),...
    uniq_genotypes...
    );

writetable(...
    array2table(...
        [av_dw_34 sd_dw_34],...
        'RowNames', uniq_genotypes,...
        'VariableNames', {'mean_DW', 'sd_DW'}...
        ),...
    fullfile(top_dir,'dw_ml_34.csv'),...
    'WriteRowNames', true...
    );

% fl
dw_tab = readtable(...
    fullfile(top_dir,'220404_AllData_Photorespiration_TB.xlsx'),...
    'Sheet', 'Dry Weight FL');
dw_tab(cellfun(@isempty,dw_tab.Genotype),:) = [];
uniq_genotypes = unique(dw_tab.Genotype);
av_dw_43 = cellfun(@(x)...
    mean(...
        [dw_tab.DryWeight_mg_(ismember(dw_tab.Genotype,x))/1000;
        dw_tab.DryWeight_mg__1(ismember(dw_tab.Genotype,x))/1000],...
        'omitnan'...
        ),...
    uniq_genotypes...
    );
sd_dw_43 = cellfun(@(x)...
    std(...
        [dw_tab.DryWeight_mg_(ismember(dw_tab.Genotype,x))/1000;
        dw_tab.DryWeight_mg__1(ismember(dw_tab.Genotype,x))/1000],...
        'omitnan'...
        ),...
    uniq_genotypes...
    );


writetable(...
    array2table(...
        [av_dw_43 sd_dw_43],...
        'RowNames', uniq_genotypes,...
        'VariableNames', {'mean_DW', 'sd_DW'}...
        ),...
    fullfile(top_dir,'dw_fl_43.csv'),...
    'WriteRowNames', true...
    );


%% gas exchange data
ge_tab_ml = readtable(...
    fullfile(top_dir, '220404_AllData_Photorespiration_TB.xlsx'),...
    'Sheet', 'Gas exchange data',...
    'Range', 'A2:P8'...
    );
ge_tab_ml.Properties.VariableNames(2:3) = {'mean_A', 'sd_A'};
writetable(...
    ge_tab_ml(:,1:3),...
    fullfile(top_dir, 'A_ml.csv'),...
    'WriteRowNames', true...
    );

ge_tab_fl = readtable(...
    fullfile(top_dir, '220404_AllData_Photorespiration_TB.xlsx'),...
    'Sheet', 'Gas exchange data',...
    'Range', 'R2:AG8'...
    );
ge_tab_fl.Properties.VariableNames(2:3) = {'mean_A', 'sd_A'};
writetable(...
    ge_tab_fl(:,1:3),...
    fullfile(top_dir, 'A_fl.csv'),...
    'WriteRowNames', true...
    );

%% metabolite concentrations
filename = fullfile(top_dir,'220404_AllData_Photorespiration_TB.xlsx');

sheets = {...
    'Metabolites ML control'...
    'Metabolites FL control'...
    'Metabolites ML to FL shift'...
    'Metabolites FL to ML shift'...
    };

met_conds = {'ml', 'fl', 'ml_fl', 'fl_ml'};

for i=1:numel(sheets)
    [met_table, av_per_genotype, sd_per_genotype, genotype, time_in_shift] = ...
        parseMetaboliteData(filename, sheets{i});

    writetable(...
        [...
        cell2table(genotype, 'VariableNames', {'genotype'}),...
        array2table(...
            [time_in_shift av_per_genotype / 1e6],...
            'VariableNames', [{'time'}, met_table.Properties.VariableNames(4:end)]...
        )],...
        fullfile(top_dir, ['met_' met_conds{i} '.csv'])...
        );
    
        writetable(...
        [...
        cell2table(genotype, 'VariableNames', {'genotype'}),...
        array2table(...
            [time_in_shift sd_per_genotype / 1e6],...
            'VariableNames', [{'time'}, met_table.Properties.VariableNames(4:end)]...
        )],...
        fullfile(top_dir, ['met_' met_conds{i} '_sd.csv'])...
        );
end

%% Metabolite ranges
met_range_tab = readtable(...
    fullfile(top_dir, 'metabolite_abundances.xlsx'),...
    'Range', 'A1:K81',...
    'ReadRowNames', true...
    );

writetable(...
    met_range_tab,...
    fullfile(top_dir, 'met_ranges.csv'),...
    'WriteRowNames', true...
    );

function [met_table,av_per_genotype,sd_per_genotype,genotype,shifttime] = parseMetaboliteData(filename,sheet)

% read table from file
met_table = readtable(filename,'Sheet',sheet);

% sort by genotype and time point
[~,idx_sort_geno] = sort(met_table.Genotype);
met_table = met_table(idx_sort_geno,:);

% create unique strings for genotype and timeshift
geno_time = strcat(...
    met_table.Genotype,...
    num2str(met_table.TimeInLightShift_h_)...
    );
[uniq_geno_time,ia] = unique(geno_time,'stable');
genotype = met_table.Genotype(ia);
shifttime = met_table.TimeInLightShift_h_(ia);

% take average over replicates (genotype and timeshift)
av_per_genotype = cell2mat(...
    cellfun(@(x)...
        mean(met_table{ismember(geno_time,x),4:end},1,'omitnan'),...
        uniq_geno_time,...
        'un',0 ...
        )...
    );

sd_per_genotype = cell2mat(...
    cellfun(@(x)...
        std(met_table{ismember(geno_time,x),4:end},1,'omitnan'),...
        uniq_geno_time,...
        'un',0 ...
        )...
    );
end

